---
title: Jekyll I18n
description: A boilerplate solution for plugin-free multilingual sites.
url: https://letrastudio.github.io
baseurl: /jekyll-i18n
github_username: letrastudio

timezone: Europe/Lisbon
lang: [en-US, pt-PT, es-ES, zh-Hant]
locales:
  en-US:
    name: English
    baseurl: /
  pt-PT:
    name: Português
    baseurl: /pt
  es-ES:
    name: Español
    baseurl: /es
  zh-Hant:
    name: 繁體中文
    baseurl: /zh

collections_dir: collections
collections:
  pages:
    output: true
    permalink: /:path/
  pages_pt:
    output: true
    permalink: /pt/:path/
  pages_es:
    output: true
    permalink: /es/:path/
  pages_zh:
    output: true
    permalink: /zh/:path/
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/
  posts_pt:
    output: true
    permalink: /pt/:categories/:year/:month/:day/:title/
  posts_es:
    output: true
    permalink: /es/:categories/:year/:month/:day/:title/
  posts_zh:
    output: true
    permalink: /zh/:categories/:year/:month/:day/:title/
  photos:
    output: true
    permalink: /photos/:path/
  photos_pt:
    output: true
    permalink: /pt/fotografias/:path/

defaults:
- scope:
    path: ''
  values:
    lang: en-US
- scope:
    path: ''
    type: pages
  values:
    layout: page
    lang: en-US
- scope:
    path: ''
    type: pages_pt
  values:
    layout: page
    lang: pt-PT
- scope:
    path: ''
    type: pages_es
  values:
    layout: page
    lang: es-ES
- scope:
    path: ''
    type: pages_zh
  values:
    layout: page
    lang: zh-Hant
- scope:
    path: ''
    type: posts
  values:
    layout: post
    lang: en-US
- scope:
    path: ''
    type: posts_pt
  values:
    layout: post
    lang: pt-PT
- scope:
    path: ''
    type: posts_es
  values:
    layout: post
    lang: es-ES
- scope:
    path: ''
    type: posts_zh
  values:
    layout: post
    lang: zh-Hant
- scope:
    path: ''
    type: photos
  values:
    layout: photo
    lang: en-US
- scope:
    path: ''
    type: photos_pt
  values:
    layout: photo
    lang: pt-PT
