---
title: Jekyll I18n
url: https://letrastudio.github.io
baseurl: /jekyll-i18n
repository: letrastudio/jekyll-i18n
description: A sane plugin-free solution for internationalized Jekyll sites.

locales:
  default:
    name: English
    lang: en-US
  pt:
    name: Português
    lang: pt-PT
  mo:
    name: 繁體中文
    lang: zh-MO
  ae:
    name: عربى
    lang: ar-AE
    direction: rtl

collections:
  posts:
    permalink: /blog/:categories/:title/
  posts/mo:
    permalink: /boke/:categories/:title/
  posts/ae:
    permalink: /mudawana/:categories/:title/
  pages:
    output: true
    permalink: /:path/
  photos:
    output: true
    permalink: /photos/:path/
  photos/pt:
    permalink: /fotografias/:path/
  photos/mo:
    output: false
  photos/ae:
    output: false

permalink: pretty

defaults:
- scope:
    type: pages
    path: ""
  values:
    layout: page
- scope:
    type: posts
    path: ""
  values:
    layout: post
- scope:
    type: photos
    path: ""
  values:
    layout: photo

plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
- jekyll-github-metadata

navigation:
- index
- about
- blog
- photos
