---
title: Jekyll I18n
url: https://letrastudio.github.io
baseurl: /jekyll-i18n
github_username: letrastudio

locales:
  default:
    name: English
    lang: en
  pt:
    name: Português
    lang: pt-PT
  zh:
    name: 繁體中文
    lang: zh-Hant
  ar:
    name: عربى
    lang: ar
    direction: rtl

collections_dir: collections
collections:
  pages:
    output: true
    permalink: /:path/
  pages_pt:
    output: true
    permalink: /pt/:path/
  pages_zh:
    output: true
    permalink: /zh/:path/
  pages_ar:
    output: true
    permalink: /ar/:path/
  posts:
    output: true
    permalink: /blog/:categories/:title/
  posts_pt:
    output: true
    permalink: /pt/blog/:categories/:title/
  posts_zh:
    output: true
    permalink: /zh/boke/:categories/:title/
  posts_ar:
    output: true
    permalink: /ar/mudawana/:categories/:title/
  photos:
    output: true
    permalink: /photos/:path/
  photos_pt:
    output: true
    permalink: /pt/fotografias/:path/

defaults:
- scope:
    path: ''
  values:
    locale: default
- scope:
    path: ''
    type: pages
  values:
    layout: page
    locale: default
- scope:
    path: ''
    type: pages_pt
  values:
    layout: page
    locale: pt
- scope:
    path: ''
    type: pages_zh
  values:
    layout: page
    locale: zh
- scope:
    path: ''
    type: pages_ar
  values:
    layout: page
    locale: ar
- scope:
    path: ''
    type: posts
  values:
    layout: post
    locale: default
- scope:
    path: ''
    type: posts_pt
  values:
    layout: post
    locale: pt
- scope:
    path: ''
    type: posts_zh
  values:
    layout: post
    locale: zh
- scope:
    path: ''
    type: posts_ar
  values:
    layout: post
    locale: ar
- scope:
    path: ''
    type: photos
  values:
    layout: photo
    locale: default
- scope:
    path: ''
    type: photos_pt
  values:
    layout: photo
    locale: pt
