---
title: Jekyll Vanilla I18n
timezone: UTC
collections:
  pages_ae:
    title: Pages AE
    output: true
    permalink: "/ae/:path/"
  pages:
    title: Pages EN
    output: true
    permalink: "/:path/"
  pages_mo:
    title: Pages MO
    output: true
    permalink: "/mo/:path/"
  pages_pt:
    title: Pages PT
    output: true
    permalink: "/pt/:path/"
  photos:
    title: Photos
    output: true
    permalink: "/photos/:path/"
  photos_pt:
    title: Photos PT
    output: true
    permalink: "/pt/fotografias/:path/"
  posts:
    title: Posts
    output: true
  posts_ae:
    title: Posts AE
    output: true
    permalink: "/ae/mudawana/:categories/:title/"
  posts_mo:
    title: Posts MO
    output: true
    permalink: "/mo/boke/:categories/:title/"
  posts_pt:
    title: Posts PT
    output: true
    permalink: "/pt/blog/:categories/:title/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    locale: default
- scope:
    path: ''
    type: pages
  values:
    layout: page
    locale: default
    lang: en
- scope:
    path: ''
    type: pages_pt
  values:
    layout: page
    locale: pt
    lang: pt-PT
- scope:
    path: ''
    type: pages_mo
  values:
    layout: page
    locale: mo
    lang: zh-Hant-MO
- scope:
    path: ''
    type: pages_ae
  values:
    layout: page
    locale: ae
    lang: ar-AE
- scope:
    path: ''
    type: posts
  values:
    layout: post
    locale: default
    lang: en
- scope:
    path: ''
    type: posts_pt
  values:
    layout: post
    locale: pt
    lang: pt-PT
- scope:
    path: ''
    type: posts_mo
  values:
    layout: post
    locale: mo
    lang: zh-Hant-MO
- scope:
    path: ''
    type: posts_ae
  values:
    layout: post
    locale: ae
    lang: ar-AE
- scope:
    path: ''
    type: photos
  values:
    layout: photo
    locale: default
    lang: en
- scope:
    path: ''
    type: photos_pt
  values:
    layout: photo
    locale: pt
    lang: pt-PT
url: https://letrastudio.github.io
baseurl: "/jekyll-i18n"
repository: letrastudio/jekyll-i18n
description: A sane, plugin-free solution for internationalized Jekyll sites.
twitter:
  username: letrastudio
locales:
  default:
    name: English
    lang: en
  pt:
    name: Português
    lang: pt-PT
  mo:
    name: 繁體中文
    lang: zh-Hant-MO
  ae:
    name: عربى
    lang: ar-AE
    direction: rtl
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
- jekyll-github-metadata
exclude:
- README.markdown
- LICENSE
